name: Build
on:
  push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Restore node_modules
        uses: actions/cache@v2
        id: pnpm-cache-dir
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: |
            node_modules
            */*/node_modules
      - name: Dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Buiild
        run: pnpm prebuild && pnpm build
