name: Build
on:
  push:
    branches:
      - main
      - develop
jobs:
  Test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Restore node_modules
        uses: actions/cache@v2
        id: pnpm-cache-dir
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: |
            node_modules
            */*/node_modules
      - name: Dependencies
        run: pnpm install
      - name: Test
        run: pnpm test

  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Restore node_modules
        uses: actions/cache@v2
        id: pnpm-cache-dir
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: |
            node_modules
            */*/node_modules
      - name: Dependencies
        run: pnpm install
      - name: Build
        run: pnpm prebuild && pnpm build
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_REGISTRY }}/watch2discord:${{ github.ref_name }}
